export const ErrorsCodes = {
    inadmissibleSymbol: 3,
    forbiddenCharacter: 6,
    nameNotDescribed: 104,
    breakOutOfLoop: 105,
    identifierAlreadyUsed: 106,
    variableNotDeclared: 107,
    constantOrVariableNotDeclared: 108,
    typesMismatch: 109,
    typeNotDeclared: 110,
    indexIsOutOfRange: 111,
    identifierExpected: 112,
    elementIsNotInitialized: 113,
    notCallableElement: 114,
    arrayExpected: 115,
}